### PR TITLE
CLI: Assign :database_path to value from 'database-path' in options.

### LINKED ISSUE #15: Multi-Word CLI Arugments Not Respected
**Describe the bug**
When passing in a CLI argument that is handled by Thor's `method_option`, multi-word arguments are [accessed by a symbol](https://github.com/rtfpessoa/dependency_spy/blob/master/lib/dependency_spy.rb#L36) instead of the string it's keyed on. This works for single word arguments as the symbolization is seamless.

The only option I can see that is affected by this is currently `database-path`

**To Reproduce**
1. Clone repo
2. Execute `bundle exec bin/depspy check --database-path="/an/invalid/path"`
3. See list of vulns, as it's defaulting to `YAVDB::Constants::DEFAULT_YAVDB_DATABASE_PATH`

**Expected behavior**
1. Execute `bundle exec bin/depspy check --database-path="/an/invalid/path"`
2. See no vulns as database is empty/invalid

**Screenshots**
Modified `dependency_spy.rb` to show options handling output:
```ruby
module DependencySpy
  class API

    def self.check(options)

      puts "=== Options Input:"
      puts options
      puts "=== Single Word Key"
      puts options["files"]
      puts options[:files]
      puts "=== Multi-Word Key"
      puts options["database-path"]
      puts options[:database_path]

      # ...
      # Original Options Handling
      # ...

      puts "=== Post Options Handling"
      puts files
      puts database_path
#...
```

Output of logging:
```
bundle exec bin/depspy check --files=Gemfile,Gemfile.lock --database-path="/an/invalid/path"
=== Options Input:
{"verbose"=>false, "path"=>"/Users/bryanculver/Workspace/Repos/OpenSource/dependency_spy", "formatter"=>"text", "database-path"=>"/an/invalid/path", "offline"=>false, "severity-threshold"=>"low", "with-color"=>true, "ignore"=>[], "files"=>"Gemfile,Gemfile.lock"}
=== Single Word Key
Gemfile,Gemfile.lock
Gemfile,Gemfile.lock
=== Multi-Word Key
/an/invalid/path

=== Post Options Handling
Gemfile,Gemfile.lock
/Users/bryanculver/.yavdb/yavdb/database
```

**Desktop (please complete the following information):**
 - OS: Mac
 - Ruby Version 2.5.5
 - Bundler Version: 1.17.3
 - Version `@master`/`v0.5.0`

**Additional context**
Discovered this while looking to implement #5.

### PR DESCRIPTION
**Pull request by bryanculver**
Simple handling for multi-word argument name.
Only 'database-path' is passed into ::API check function.

Likely backward compatible as setting was never honored before.

Closes #15.

### CODE REVIEW

File: lib/dependency_spy/cli.rb [hunk 1]
```diff
@@ -51,7 +51,10 @@ class CLI < Thor
     method_option('with-color', :type => :boolean, :default => true)
     method_option('ignore', :aliases => :i, :type => :array, :default => [])
     def check
-      manifests = API.check(options)
+      the_options = options.dup
+      the_options[:database_path] = the_options[:"database-path"]
```
Comment (rtfpessoa) [inline lib/dependency_spy/cli.rb]: I am definitely not an expert with Ruby, but the fix seems a bit hackish since it just works for that instance.

I would prefer to go for using it like the others e.g.: `options['output-path']` or to even stop using the symbols and use strings everywhere.

What do you think?

Comment (bryanculver) [reply lib/dependency_spy/cli.rb]: So since the CLI wraps the API model, I didn't want to suggest changing the API for a specific implementation (called via CLI vs importing). I figured this was cleaner as it won't break anyone/anything that already directly imports the API model.

In theory, the API model could be refactored out into its own repo and be an import if it was desired to remove all forms of implementation from the API handler.

As well, because these are relatively "fixed" arguments for the API (there are only a certain number of parameters and it's not like the keys are DB indexes), I figured using something immutable (the symbols) would be a better access method than strings themselves. (See: https://rubyinrails.com/2013/08/29/difference-between-symbols-and-strings/ and https://github.com/github/rubocop-github/blob/master/STYLEGUIDE.md#keyword-arguments). There are minor performance differences between Symbols vs Strings, the former being _slightly_ faster, but that really isn't measurable in this use case.

Because the latter options are specific to the CLI implementation I felt it was fine to leave them as is. They aren't "adapting" themselves to the required arguments of another model. This PR was directly solving a bug in the implementation. If a stylistic choice is made, then I could certainly raise a PR refactoring them to conform to the decided style.

I had to `dup` the options as it's frozen when passed in via Thor.

Comment (rtfpessoa) [reply lib/dependency_spy/cli.rb]: Fair enough I will merge it and then will think a bit better about the next steps.
